const headerHTML=`<header><a class="brand" href="index.html"><img src="graphics/SCANAPP_COLOR.png" alt="ScanApp"></a><button class="menu" type="button" aria-label="Menu" aria-expanded="false" aria-controls="site-navigation">☰</button><nav id="site-navigation"><a href="index.html">About</a><div class="drop"><a href="features.html">Features</a><div class="dropmenu"><a href="receiving.html">Receiving</a><a href="invoicing.html">Invoicing</a><a href="lpo.html">LPO Management</a><a href="faq.html">FAQ</a><a href="howtos.html">How-Tos</a></div></div><a href="results.html">Results</a><a href="contact.html">Contact</a><a class="demo-nav" href="request-demo.html" data-demo-link>Request a Demo</a><a class="login-btn" href="https://thescan.app">Login</a></nav></header>`;
const footerHTML=`<footer class="footer"><img src="graphics/POWER%20SYSTEMS%20LOGO_WHITE.png" alt="Power Systems Inc."><div>ScanApp · Power Systems Inc. · Ottawa, Canada · Call or Text: <a href="tel:+16132823283">613.282.3283</a> · <span data-email></span></div></footer>`;
document.querySelectorAll('[data-site-header]').forEach(el=>el.innerHTML=headerHTML);
document.querySelectorAll('[data-site-footer]').forEach(el=>el.innerHTML=footerHTML);
// One shared menu implementation for every page, including Contact.
const btn = document.querySelector('[data-site-header] .menu');
const navigation = document.querySelector('[data-site-header] nav');
if (btn && navigation) {
  btn.addEventListener('click', () => {
    navigation.classList.toggle('open');
    btn.setAttribute('aria-expanded', String(navigation.classList.contains('open')));
  });
  document.addEventListener('keydown', event => {
    if (event.key === 'Escape' && navigation.classList.contains('open')) {
      navigation.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
      btn.focus();
    }
  });
}
const ep=['info','powersystemsinc.ca'];document.querySelectorAll('[data-email]').forEach(el=>{const a=document.createElement('a');a.href='mail'+'to:'+ep[0]+'@'+ep[1];a.textContent=ep[0]+'@'+ep[1];el.replaceWith(a);});

// Match both .html pages and Netlify clean URLs; the root is the About page.
function updateActiveNavigation(pathname) {
  const pageKey = path => path.replace(/\/+$/, '').split('/').pop().replace(/\.html$/i, '').toLowerCase() || 'index';
  const links = Array.from(document.querySelectorAll('[data-site-header] nav a[href]'));
  const currentPage = pageKey(pathname);

  links.forEach(link => {
    link.classList.remove('is-active');
    link.removeAttribute('aria-current');
  });

  const currentLink = links.find(link =>
    pageKey(new URL(link.getAttribute('href'), document.baseURI).pathname) === currentPage
  );
  if (!currentLink) return;

  currentLink.classList.add('is-active');
  currentLink.setAttribute('aria-current', 'page');

  // Feature detail pages also underline Features, without marking it as the page.
  const dropdown = currentLink.closest('.dropmenu');
  if (dropdown) {
    const sectionLink = dropdown.parentElement.querySelector(':scope > a');
    if (sectionLink) sectionLink.classList.add('is-active');
  }
}
updateActiveNavigation(window.location.pathname);

// Site-wide lead-intent tracking. No navigation interception or extra GA config.
(() => {
  if (window.__scanAppLeadTracking) return;
  window.__scanAppLeadTracking = true;
  const measurementId = 'G-S8TZXDFMCD';
  const handledEvents = new WeakSet();

  function send(name, parameters = {}) {
    try {
      if (typeof window.gtag !== 'function') return;
      window.gtag('event', name, {
        send_to: measurementId,
        transport_type: 'beacon',
        page_path: window.location.pathname,
        ...parameters
      });
    } catch (_) {
      // Analytics must never prevent a visitor from contacting us.
    }
  }

  // Delegation includes links generated by the header/footer and contact.js.
  // Capture ensures existing handlers cannot hide an activation from tracking.
  document.addEventListener('click', event => {
    if (event.button !== 0 || handledEvents.has(event)) return;
    const target = event.target instanceof Element ? event.target : event.target?.parentElement;
    const control = target?.closest('a[href], button[data-demo-cta]');
    if (!control || control.matches(':disabled, [aria-disabled="true"]')) return;
    handledEvents.add(event);
    if (control.matches('[data-demo-cta], [data-demo-link]')) {
      send('demo_cta_click');
    }
    const href = (control.getAttribute('href') || '').trim();
    // Never send addresses, phone numbers or mailto subject/body to Analytics.
    if (/^mailto:/i.test(href)) send('email_click');
    else if (/^tel:/i.test(href)) send('phone_click');
  }, true);

  // Query strings and hashes are excluded by pathname; support Netlify clean URLs.
  if (/\/contact(?:\.html)?\/?$/i.test(window.location.pathname)) {
    send('contact_view');
  }
})();
